name: Firestore Storage Rules production CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'storage-rules.rules'
      - 'storage-test-rules.rules'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: Main
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Firestore Storage Rules
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only storage
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_DEPLOY_SA }}